(() => {
  const KEY='murimAudioSettingsV4',defaults={master:.90,music:.52,sfx:.76,musicOn:true,sfxOn:true};let settings={...defaults};try{settings={...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{}
  const BGM={home:'assets/audio/bgm_home.mp3',forest:'assets/audio/bgm_bamboo.mp3',frost:'assets/audio/bgm_snow.mp3',ember:'assets/audio/bgm_canyon.mp3',crypt:'assets/audio/bgm_tomb.mp3',boss:'assets/audio/bgm_boss.mp3'};
  const SFX={ui:'assets/audio/sfx_ui.mp3',sword:'assets/audio/sfx_sword.mp3',dagger:'assets/audio/sfx_dagger.mp3',bow:'assets/audio/sfx_bow.mp3',fan:'assets/audio/sfx_fan.mp3',hammer:'assets/audio/sfx_hammer.mp3',spear:'assets/audio/sfx_spear.mp3',ring:'assets/audio/sfx_ring.mp3',talisman:'assets/audio/sfx_talisman.mp3',hit:'assets/audio/sfx_hit.mp3',heavyHit:'assets/audio/sfx_heavy.mp3',chestHit:'assets/audio/sfx_chest_hit.mp3',chestBreak:'assets/audio/sfx_chest_break.mp3',pickup:'assets/audio/sfx_pickup.mp3',rare:'assets/audio/sfx_rare.mp3',boss:'assets/audio/sfx_boss.mp3',heal:'assets/audio/sfx_heal.mp3',success:'assets/audio/sfx_success.mp3',fail:'assets/audio/sfx_fail.mp3'};
  const SK=['flame','lightning','frost','meteor','blades','ward','poison','orbit','laser','shadow','wind','quake','dragonHeart','stormCore','starSigil','worldSeed','moonSeal','primalCore','infernoCyclone','stormNova','astralAegis','verdantPlague','eclipseRay','tempestRift'];const SKILL={};for(const k of SK)SKILL[k]=`assets/audio/sfx_skill_${k}.mp3`;
  let bgm=null,currentMode='none',unlocked=false;const pool=new Map(),last={};const persist=()=>{try{localStorage.setItem(KEY,JSON.stringify(settings))}catch{}};const mv=()=>Math.max(0,Math.min(1,settings.master*settings.music)),sv=()=>Math.max(0,Math.min(1,settings.master*settings.sfx));
  function make(src,loop=false){const a=new Audio(src);a.preload='auto';a.loop=loop;a.playsInline=true;a.setAttribute('playsinline','');return a}function unlock(){unlocked=true;return Promise.resolve(true)}
  async function playMusic(mode='home',force=false){currentMode=mode;if(!settings.musicOn)return false;const src=BGM[mode]||BGM.home;if(bgm&&!force&&bgm.dataset.mode===mode&&!bgm.paused)return true;if(bgm){try{bgm.pause();bgm.currentTime=0}catch{}}bgm=make(src,true);bgm.dataset.mode=mode;bgm.volume=mv();try{await bgm.play();return true}catch(e){console.warn('BGM blocked',e);return false}}
  function stopMusic(){if(bgm){try{bgm.pause();bgm.currentTime=0}catch{}}}function play(src,key,gap=70){if(!settings.sfxOn||!src)return;const n=performance.now();if(n-(last[key]||0)<gap)return;last[key]=n;let arr=pool.get(src);if(!arr){arr=[make(src),make(src),make(src)];pool.set(src,arr)}let a=arr.find(x=>x.paused||x.ended)||arr[0];try{a.currentTime=0}catch{}a.volume=sv();a.play()?.catch?.(()=>{})}
  const sfx={};for(const [k,src] of Object.entries(SFX))sfx[k]=()=>play(src,k,k==='hit'?55:k==='sword'?90:70);function skill(id){play(SKILL[id]||SFX.talisman,'skill_'+id,180)}
  function set(part,val){if(part==='musicOn'||part==='sfxOn')settings[part]=!!val;else settings[part]=Math.max(0,Math.min(1,Number(val)||0));persist();if(bgm)bgm.volume=mv();if(part==='musicOn'){if(settings.musicOn)playMusic(currentMode==='none'?'home':currentMode,true);else stopMusic()}}
  function mapMode(id){return ({forest:'forest',frost:'frost',ember:'ember',crypt:'crypt'})[id]||'forest'}function state(){return {supported:true,state:unlocked?'ready':'tap-required',musicMode:currentMode,playingMode:bgm&&!bgm.paused?currentMode:'none',settings:{...settings}}}function resetSettings(){settings={...defaults};persist();if(bgm)bgm.volume=mv();playMusic(currentMode==='none'?'home':currentMode,true)}async function test(){unlock();settings.musicOn=settings.sfxOn=true;persist();const ok=await playMusic('home',true);sfx.sword();setTimeout(()=>skill('flame'),220);return ok}
  document.addEventListener('visibilitychange',()=>{if(document.hidden){if(bgm)bgm.pause()}else if(settings.musicOn&&currentMode!=='none')playMusic(currentMode,true)});window.addEventListener('pageshow',()=>{if(settings.musicOn&&currentMode!=='none')playMusic(currentMode,true)});window.MurimAudio={settings,set,unlock,playMusic,stopMusic,mapMode,sfx,skill,state,resetSettings,defaults,test};
})();
