(() => {
  const A=window.MurimAudio;if(!A)return;const $a=id=>document.getElementById(id);
  const homePanel=document.querySelector('#startScreen .heroPanel');
  if(homePanel&&!$a('audioSettingsBtn')){const b=document.createElement('button');b.id='audioSettingsBtn';b.className='btn ghost wide audioSettingsBtn';b.textContent='🎵 소리 설정';homePanel.appendChild(b)}
  const overlay=document.createElement('div');overlay.id='audioSettingsScreen';overlay.className='overlay hidden';
  overlay.innerHTML=`<div class="panel"><div class="sectionTitle"><h2>🎵 소리 설정</h2><span id="audioStateText">오디오 준비</span></div><p class="subtitle">BGM은 음악 파일로 재생하고, 전투 효과음은 지연이 적은 버퍼 방식으로 재생합니다.</p><div class="audioRow"><label>전체</label><input id="audMaster" type="range" min="0" max="1" step="0.01"><span class="audioValue" id="audMasterV"></span></div><div class="audioRow"><label>배경음악</label><input id="audMusic" type="range" min="0" max="1" step="0.01"><span class="audioValue" id="audMusicV"></span></div><div class="audioRow"><label>효과음</label><input id="audSfx" type="range" min="0" max="1" step="0.01"><span class="audioValue" id="audSfxV"></span></div><div class="toggleRow"><span>배경음악 사용</span><button class="toggleBtn" id="audMusicOn"></button></div><div class="toggleRow"><span>효과음 사용</span><button class="toggleBtn" id="audSfxOn"></button></div><div class="btnRow mt12"><button class="btn gold" id="audioTestBtn">▶ 소리 점검</button><button class="btn ghost" id="audioResetBtn">설정 초기화</button></div><button class="btn secondary wide mt12" id="audioBackBtn">돌아가기</button></div>`;document.body.appendChild(overlay);
  function sync(){const s=A.settings;$a('audMaster').value=s.master;$a('audMusic').value=s.music;$a('audSfx').value=s.sfx;$a('audMasterV').textContent=Math.round(s.master*100)+'%';$a('audMusicV').textContent=Math.round(s.music*100)+'%';$a('audSfxV').textContent=Math.round(s.sfx*100)+'%';$a('audMusicOn').textContent=s.musicOn?'켜짐':'꺼짐';$a('audMusicOn').classList.toggle('on',s.musicOn);$a('audSfxOn').textContent=s.sfxOn?'켜짐':'꺼짐';$a('audSfxOn').classList.toggle('on',s.sfxOn);const st=A.state();$a('audioStateText').textContent=st.playingMode!=='none'?`BGM 재생 중 · 효과음 ${st.decoded||0}개 준비`:'재생 준비됨'}
  $a('audMaster').oninput=e=>{A.set('master',e.target.value);sync()};$a('audMusic').oninput=e=>{A.set('music',e.target.value);sync()};$a('audSfx').oninput=e=>{A.set('sfx',e.target.value);sync()};
  $a('audMusicOn').onclick=()=>{A.unlock();A.set('musicOn',!A.settings.musicOn);A.sfx.ui();sync()};$a('audSfxOn').onclick=()=>{A.unlock();A.set('sfxOn',!A.settings.sfxOn);A.sfx.ui();sync()};
  $a('audioSettingsBtn').onclick=()=>{A.unlock();A.sfx.ui();sync();startScreen.classList.add('hidden');overlay.classList.remove('hidden')};
  $a('audioTestBtn').onclick=async()=>{const ok=await A.test();sync();$a('audioStateText').textContent=ok?'BGM/검격/무공 소리 점검 중':'BGM 재생 차단됨'};
  $a('audioResetBtn').onclick=()=>{A.resetSettings();A.sfx.ui();sync()};$a('audioBackBtn').onclick=()=>{A.sfx.ui();overlay.classList.add('hidden');startScreen.classList.remove('hidden')};sync();
  document.addEventListener('click',e=>{if(e.target.closest('button')&&!e.target.closest('#audioSettingsBtn,#audioBackBtn,#audioTestBtn,#audioResetBtn'))A.sfx.ui()},true);

  const baseStart=start;start=function(){A.unlock();const r=baseStart();A.playMusic(A.mapMode(currentMap?.id||'forest'),true);return r};
  const baseFinish=finishRun;finishRun=function(cleared=false){const r=baseFinish(cleared);cleared?A.sfx.success():A.sfx.fail();A.playMusic('home',true);return r};
  const baseBoss=spawnBoss;spawnBoss=function(){const r=baseBoss();A.sfx.boss();A.playMusic('boss',true);return r};const baseMidBoss=spawnMidBoss;spawnMidBoss=function(){const r=baseMidBoss();A.sfx.boss();return r};

  const baseShoot=shoot;shoot=function(){const wt=player?.weaponType||'sword',b0=bullets.length,a0=attackEffects.length,r=baseShoot(),key={sword:'sword',dagger:'dagger',bow:'bow',staff:'fan',hammer:'hammer',spear:'spear',axe:'ring',grimoire:'talisman'}[wt];if(key&&(bullets.length>b0||attackEffects.length>a0))A.sfx[key]();return r};
  const baseCastSkill=castSkill;castSkill=function(id){const b0=bullets.length,a0=attackEffects.length,sh0=player?.shield||0,r=baseCastSkill(id);if(bullets.length>b0||attackEffects.length>a0||(player?.shield||0)>sh0)A.skill(id);return r};

  if(typeof damageChest==='function'){const f=damageChest;damageChest=function(c,amount,color){const before=c?.hp,wasBroken=!!c?.broken,r=f(c,amount,color);if(!wasBroken&&c?.broken)A.sfx.chestBreak();else if(before!=null&&c?.hp<before)A.sfx.chestHit();return r}};
  if(typeof acquireRunItem==='function'){const f=acquireRunItem;acquireRunItem=function(item){const r=f(item);if(item?.rarity&&['epic','legendary','mythic'].includes(item.rarity))A.sfx.rare();else A.sfx.pickup();return r}};
})();